name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /var/www/altertravel.ru/data/www/altertravel.pro
            && git init
            && git remote remove origin
            && git remote add origin https://github.com/andreev-e/alter-nuxt.git
            && git pull origin master
            && npm install --production
            && npm run build
            && pm2 start npm --name "altertravel.pro" -- run start
