name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /var/www/altertravel.ru/data/www/altertravel.pro
            && git init
            && git remote set-url origin git@github.com:andreev-e/alter-nuxt.git
            && git reset --hard HEAD
            && git checkout master
            && git pull origin:master master
            && npm install --production
            && npm run build
            && pm2 restart new-alter
